#version: '3'
#services:
#  app:
#    build: .
#    image: whereis-img
#    ports:
#      - 8080:8080
#    depends_on:
#      - db

#
#  db:
#    image: postgres:latest
#    container_name: db
#    environment:
#      - POSTGRES_DB=whereis-main
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin


version: '3'
services:
  app:
    build: .
    image: whereis-img
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://whereis-db.crsppowtrm9t.us-west-2.rds.amazonaws.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=whereis_admin
      - SPRING_DATASOURCE_PASSWORD=q1234567890
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update