#version: '3'
#services:
#  app:
#    build: .
#    image: whereis-img
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/whereis-main
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  db:
#    image: postgres:latest
#    container_name: db
#    environment:
#      - POSTGRES_DB=whereis-main
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin


version: '3'
services:
  app:
    build: .
    image: whereis-img
    ports:
      - 8080:8080